#!/bin/bash
# TS trace window analysis — runs 48h after TOKEN_SAVIOR_TRACE=1 was activated.
# Aggregates per-tool latency from journald + investigates set_project_root churn.
# Output:
#   - /root/.claude/projects/-root/memory/ts-latency-baseline-20260506.md
#   - Telegram ping so the next Claude session surfaces the result
set -euo pipefail

WINDOW_START="2026-05-04 12:00:00"
WINDOW_END="2026-05-06 12:00:00"
OUT_DIR="/root/.claude/projects/-root/memory"
OUT_FILE="$OUT_DIR/ts-latency-baseline-20260506.md"
RAW_LOG="/tmp/ts-trace-window.log"
TG_TOKEN="8030852062:AAGLTBDoNyfblt7RvZq5b9KICM5qeXxfFUU"
TG_CHAT="1294356923"

# 1. Extract trace lines from journal
journalctl --since "$WINDOW_START" --until "$WINDOW_END" --no-pager 2>/dev/null \
  | grep -E "token-savior|token_savior" \
  > "$RAW_LOG" || true

LINE_COUNT=$(wc -l < "$RAW_LOG")
TRACE_LINES=$(grep -cE "\-> call|elapsed_ms|<- call" "$RAW_LOG" || echo 0)

# 2. Parse and aggregate (auto-detects two known formats; fall through if neither)
python3 <<PYEOF > "$OUT_FILE"
import re
import statistics
from collections import defaultdict, Counter

raw = open("$RAW_LOG").read().splitlines()

# Format A: "[token-savior] -> call <name>" + "[token-savior] <- call <name> elapsed_ms=NNN"
# Format B: "tool=<name> elapsed_ms=NNN"
call_starts = []
elapsed = defaultdict(list)
set_root_args = []

start_re  = re.compile(r"\[token-savior\] -> call (\S+)")
end_re    = re.compile(r"\[token-savior\] <- call (\S+)\s+elapsed_ms=(\d+)")
fallback  = re.compile(r"tool=(\S+).*elapsed_ms=(\d+)")
spr_arg   = re.compile(r"set_project_root.*?(?:path|name)\s*[=:]\s*['\"]?(\S+?)['\"]?\b")

for line in raw:
    m = end_re.search(line) or fallback.search(line)
    if m:
        elapsed[m.group(1)].append(int(m.group(2)))
        continue
    m = start_re.search(line)
    if m:
        call_starts.append(m.group(1))
    if "set_project_root" in line:
        sm = spr_arg.search(line)
        if sm:
            set_root_args.append(sm.group(1))

print(f"# TS Latency Baseline — Window 2026-05-04 → 2026-05-06\n")
print(f"**Raw journal lines containing token-savior:** {len(raw)}")
print(f"**Trace lifecycle lines parsed:** {sum(len(v) for v in elapsed.values())}")
print(f"**Call-start markers seen:** {len(call_starts)}\n")

if not elapsed:
    print("> ⚠ No elapsed_ms data parsed. Either tracing was never restarted to pick up TOKEN_SAVIOR_TRACE=1, or the log format does not match start_re/end_re/fallback. Inspect a few lines from /tmp/ts-trace-window.log.\n")

if elapsed:
    rows = []
    for tool, vals in elapsed.items():
        vals.sort()
        n = len(vals)
        p50 = statistics.median(vals)
        p95 = vals[min(n - 1, int(0.95 * n))]
        rows.append((tool, n, p50, p95, sum(vals)))
    rows.sort(key=lambda r: -r[3])
    print("## Per-tool latency (sorted by p95 desc)\n")
    print("| Tool | n | p50 (ms) | p95 (ms) | Σ time (ms) |")
    print("|---|---:|---:|---:|---:|")
    for tool, n, p50, p95, tot in rows:
        print(f"| `{tool}` | {n} | {p50:.0f} | {p95:.0f} | {tot} |")
    print()

# Call frequency from start markers (only if we got them)
if call_starts:
    cnt = Counter(call_starts)
    print("## Call frequency (from start markers)\n")
    print("| Tool | Calls |")
    print("|---|---:|")
    for tool, n in cnt.most_common():
        print(f"| `{tool}` | {n} |")
    print()

# set_project_root investigation
if set_root_args:
    cnt = Counter(set_root_args)
    print("## set_project_root args breakdown\n")
    print(f"Total calls in window: {sum(cnt.values())}")
    print()
    print("| Path/name | Calls |")
    print("|---|---:|")
    for path, n in cnt.most_common():
        print(f"| \`{path}\` | {n} |")
    print()
    print("**Hypothesis check:**")
    print(f"- Single dominant project? → {'YES (hook re-register suspect)' if cnt.most_common(1)[0][1] > sum(cnt.values()) * 0.5 else 'NO'}")
    print(f"- Many distinct projects? → {'YES (UX confusion suspect)' if len(cnt) > 5 else 'NO'}")
elif call_starts and any("set_project_root" in s for s in call_starts):
    print("## set_project_root\n")
    print("Calls observed but argument parser could not extract paths — refine the regex.\n")

print("\n---\n")
print(f"_Generated by /root/token-savior/scripts/ts-trace-analysis.sh on $(date -u +%FT%TZ)_")
PYEOF

# 3. Add pointer to MEMORY.md if not already present
if ! grep -q "ts-latency-baseline-20260506" "$OUT_DIR/MEMORY.md"; then
  python3 - <<PYEOF
import pathlib
p = pathlib.Path("$OUT_DIR/MEMORY.md")
text = p.read_text()
needle = "## Sessions récentes"
insert = "- [TS latency baseline 06/05](ts-latency-baseline-20260506.md) -- p50/p95 par tool sur fenêtre 04→06/05, diag set_project_root\n"
text = text.replace(needle, insert + "\n" + needle, 1)
p.write_text(text)
PYEOF
fi

# 4. Telegram ping
SUMMARY="🧪 TS trace analysis ready — $TRACE_LINES lifecycle lines parsed. Open ts-latency-baseline-20260506.md."
curl -s -X POST "https://api.telegram.org/bot${TG_TOKEN}/sendMessage" \
  -d "chat_id=${TG_CHAT}" \
  -d "text=${SUMMARY}" > /dev/null || true

echo "Done. Summary at $OUT_FILE"
